services:
  db:
    image: mysql:8.0.30
    container_name: db_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    restart: always
    ports:
      - "6033:3306" # Exposing the container's 3306 port to host's 6033
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: pma_container
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 6033
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80

  nodejs:
    build:
      context: .
      dockerfile: nodejs.dockerfile
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: "npm start"

# The database will be persistent among containers restarts.
volumes:
  dbdata:
